# Generated by Django 5.1.6 on 2025-02-06 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("press", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newspaper",
            options={"ordering": ["-published_date"]},
        ),
    ]
